title: Victoria Henri # your name (or website title) here
logo: "/images/vhenri_logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Hello! I'm a Canadian developer on a mission to learn as much as I can. Starting early 2020, my goal is to create one project a month. Big or small. In any and all languages. I don't want to get stuck being too comfortable, so I'm challenging myself. Wish me luck! 
  <br><br>
  <a href="https://www.linkedin.com/in/victoriahenri/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://devpost.com/vhenri">View My Devpost</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-159299049-1 # your Google Analytics tracking ID here
